model: "Qwen/Qwen3-4B-Instruct-2507"
toc_check_page_num: 2
max_page_num_each_node: 10
max_token_num_each_node: 20000
if_add_node_id: "yes"
if_add_node_summary: "no"
if_add_doc_description: "yes"
if_add_node_text: "yes"